apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
  namespace: k8s-namespace
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
      - name: node-api
        image: jasmeetkaur42/k8sdevops-app:v2  
        ports:
        - containerPort: 8080

        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: db-secret

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"

        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10